name: Compile

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**/README.md'
      - '**/UPDATES.md'
      - '**/CHANGELOG'
      - '**/CONTRIBUTING.md'
      - '**/LICENSE'
      - '**/.github/**'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**/README.md'
      - '**/CHANGELOG'
      - '**/CONTRIBUTING.md'
      - '**/LICENSE'
      - '**/.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '19.0.2+7'

      - name: Build with Maven
        run: mvn -B clean install

      - name: Upload Plugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: BedWars1058-Plugin
          path: bedwars-plugin/target/*.jar

      - name: Upload API JAR
        uses: actions/upload-artifact@v4
        with:
          name: BedWars1058-API
          path: bedwars-api/target/*.jar
